import '@/docs/zodOpenApi.js';
import type { OpenAPIRegistry } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';
import {
   errorResponseSchema,
   formFieldTypeSchema,
   formQuestionStatusSchema,
   idParamSchema,
   protectedEndpoint,
   validationErrorResponseSchema,
} from '@/docs/commonSchemas.js';

const tag = 'Registration forms';

const formQuestionOptionRequestSchema = z.object({
   label: z.string().min(1),
   value: z.string().min(1),
});

const createFormQuestionRequestSchema = z.object({
   label: z.string().min(1).max(255),
   fieldType: formFieldTypeSchema,
   isRequired: z.boolean().optional(),
   helpText: z.string().nullable().optional(),
   orderIndex: z.number().int().min(0).optional(),
   options: z.array(formQuestionOptionRequestSchema).optional(),
});

const updateFormQuestionRequestSchema = z.object({
   label: z.string().min(1).max(255).optional(),
   fieldType: formFieldTypeSchema.optional(),
   isRequired: z.boolean().optional(),
   helpText: z.string().nullable().optional(),
   orderIndex: z.number().int().min(0).optional(),
   status: formQuestionStatusSchema.optional(),
});

const formQuestionOptionSchema = z.object({
   id: z.string(),
   formQuestionId: z.string(),
   label: z.string(),
   value: z.string(),
   isActive: z.boolean(),
   createdAt: z.string().datetime(),
   createdBy: z.string(),
   updatedAt: z.string().datetime().nullable(),
   updatedBy: z.string().nullable(),
});

const formQuestionSchema = z.object({
   id: z.string(),
   registrationFormId: z.string(),
   label: z.string(),
   fieldKey: z.string(),
   fieldType: formFieldTypeSchema,
   isRequired: z.boolean(),
   helpText: z.string().nullable(),
   orderIndex: z.number(),
   status: formQuestionStatusSchema,
   createdAt: z.string().datetime(),
   createdBy: z.string(),
   updatedAt: z.string().datetime().nullable(),
   updatedBy: z.string().nullable(),
   options: z.array(formQuestionOptionSchema),
});

const formQuestionMutationResponseSchema = z.object({
   msg: z.literal('success'),
   data: formQuestionSchema,
});

export const registerRegistrationFormDocs = (registry: OpenAPIRegistry) => {
   const CreateFormQuestionRequest = registry.register(
      'CreateFormQuestionRequest',
      createFormQuestionRequestSchema,
   );
   const UpdateFormQuestionRequest = registry.register(
      'UpdateFormQuestionRequest',
      updateFormQuestionRequestSchema,
   );
   const FormQuestionMutationResponse = registry.register(
      'FormQuestionMutationResponse',
      formQuestionMutationResponseSchema,
   );

   registry.registerPath({
      method: 'post',
      path: '/api/registration-form/{id}/question',
      tags: [tag],
      summary: 'Create a form question',
      description:
         'Requires authentication, manage_events permission, and either Admin ' +
         'role or steering committee membership on the parent event. Only draft ' +
         'forms without responses can be edited. Field keys are generated by ' +
         'the backend and kept unique within the form.',
      security: [protectedEndpoint],
      request: {
         params: idParamSchema,
         body: {
            required: true,
            content: {
               'application/json': {
                  schema: CreateFormQuestionRequest,
               },
            },
         },
      },
      responses: {
         201: {
            description: 'Form question created.',
            content: {
               'application/json': {
                  schema: FormQuestionMutationResponse,
               },
            },
         },
         400: {
            description: 'Validation error or form is not editable.',
            content: {
               'application/json': {
                  schema: validationErrorResponseSchema.or(errorResponseSchema),
               },
            },
         },
         401: { description: 'Authentication required.' },
         403: {
            description:
               'Missing manage_events permission, Admin role, or steering committee membership.',
         },
         404: {
            description: 'Registration form not found.',
            content: {
               'application/json': {
                  schema: errorResponseSchema,
               },
            },
         },
      },
   });

   registry.registerPath({
      method: 'patch',
      path: '/api/registration-form/question/{id}',
      tags: [tag],
      summary: 'Update a form question',
      description:
         'Requires authentication, manage_events permission, and either Admin ' +
         'role or steering committee membership on the parent event. Only draft ' +
         'forms without responses can be edited.',
      security: [protectedEndpoint],
      request: {
         params: idParamSchema,
         body: {
            required: true,
            content: {
               'application/json': {
                  schema: UpdateFormQuestionRequest,
               },
            },
         },
      },
      responses: {
         200: {
            description: 'Form question updated.',
            content: {
               'application/json': {
                  schema: FormQuestionMutationResponse,
               },
            },
         },
         400: {
            description: 'Validation error or form is not editable.',
            content: {
               'application/json': {
                  schema: validationErrorResponseSchema.or(errorResponseSchema),
               },
            },
         },
         401: { description: 'Authentication required.' },
         403: {
            description:
               'Missing manage_events permission, Admin role, or steering committee membership.',
         },
         404: {
            description: 'Form question not found.',
            content: {
               'application/json': {
                  schema: errorResponseSchema,
               },
            },
         },
      },
   });

   registry.registerPath({
      method: 'patch',
      path: '/api/registration-form/question/delete/{id}',
      tags: [tag],
      summary: 'Delete a form question',
      description:
         'Requires authentication, manage_events permission, and either Admin ' +
         'role or steering committee membership on the parent event. Soft ' +
         'deletes the question and deactivates related options.',
      security: [protectedEndpoint],
      request: {
         params: idParamSchema,
      },
      responses: {
         200: {
            description: 'Form question deleted.',
            content: {
               'application/json': {
                  schema: FormQuestionMutationResponse,
               },
            },
         },
         400: {
            description: 'Validation error or form is not editable.',
            content: {
               'application/json': {
                  schema: validationErrorResponseSchema.or(errorResponseSchema),
               },
            },
         },
         401: { description: 'Authentication required.' },
         403: {
            description:
               'Missing manage_events permission, Admin role, or steering committee membership.',
         },
         404: {
            description: 'Form question not found.',
            content: {
               'application/json': {
                  schema: errorResponseSchema,
               },
            },
         },
      },
   });
};
